# historical_events.py

historical_events = {
        1822: 'Brazil declares independence from Portugal.',
        1823: 'Monroe Doctrine established, declaring U.S. opposition to European interference in the Americas.',
        1824: 'The Great Fire of Dublin.',
        1825: 'Erie Canal opens in the United States.',
        1826: 'Photography is invented.',
        1827: 'Greek War of Independence begins.',
        1828: 'The first passenger railway in the world opens in England.',
        1829: 'The Metropolitan Police Service is founded in London.',
        1830: 'The first regular passenger train service begins in England.',
        1831: 'Belgium gains independence from the Netherlands.',
        1832: 'The Reform Act in the United Kingdom expands voting rights.',
        1833: 'Slavery abolished in the British Empire.',
        1834: 'The Spanish Inquisition is officially disbanded.',
        1835: 'The Great Fire of New York.',
        1836: 'Texas declares independence from Mexico.',
        1837: 'Queen Victoria ascends to the throne in the United Kingdom.',
        1838: 'The People\'s Charter calls for voting reform in the United Kingdom.',
        1839: 'First Opium War begins between China and Great Britain.',
        1840: 'Antarctica is sighted for the first time.',
        1841: 'Hong Kong is ceded to Great Britain.',
        1842: 'The Mines Act in the United Kingdom restricts child labor in coal mines.',
        1843: 'Charles Dickens publishes "A Christmas Carol."',
        1844: 'The first telegraph line is completed in the United States.',
        1845: 'The Irish Potato Famine begins.',
        1846: 'The Smithsonian Institution is established in the United States.',
        1847: 'The Communist Manifesto is published.',
        1848: 'Revolutions sweep across Europe.',
        1849: 'Gold Rush begins in California.',
        1850: 'The Compromise of 1850 is passed in the United States.',
        1851: 'The Great Exhibition is held in London\'s Crystal Palace.',
        1852: 'Harriet Beecher Stowe publishes "Uncle Tom\'s Cabin."',
        1853: 'Crimean War begins.',
        1854: 'The Charge of the Light Brigade during the Crimean War.',
        1855: 'Walt Whitman publishes "Leaves of Grass."',
        1856: 'Suez Canal construction begins.',
        1857: 'Indian Rebellion against British rule.',
        1858: 'The first transatlantic telegraph cable is completed.',
        1859: 'Charles Darwin publishes "On the Origin of Species."',
        1860: 'Abraham Lincoln elected President of the United States.',
        1861: 'American Civil War begins.',
        1862: 'Homestead Act signed in the United States.',
        1863: 'The Emancipation Proclamation is issued in the United States.',
        1864: 'Red Cross is founded.',
        1865: 'The Civil War ends in the United States.',
        1866: 'Austro-Prussian War.',
        1867: 'Alaska is purchased from Russia by the United States.',
        1868: 'The 14th Amendment is ratified in the United States.',
        1869: 'The Suez Canal opens.',
        1870: 'Franco-Prussian War.',
        1871: 'German Empire is established.',
        1872: 'The first national park, Yellowstone, is established in the United States.',
        1873: 'Panic of 1873 begins an economic depression.',
        1874: 'Impressionist art movement begins.',
        1875: 'The Pacific Cable is completed, connecting North America to Asia.',
        1876: 'Alexander Graham Bell invents the telephone.',
        1877: 'Reconstruction ends in the United States.',
        1878: 'Thomas Edison patents the phonograph.',
        1879: 'Anglo-Zulu War.',
        1880: 'First electric streetlights installed in the United States.',
        1881: 'Assassination of Tsar Alexander II of Russia.',
        1882: 'The Triple Alliance is formed in Europe.',
        1883: 'The Brooklyn Bridge opens.',
        1884: 'The International Meridian Conference establishes Greenwich Mean Time.',
        1885: 'Mahdist forces capture Khartoum.',
        1886: 'Haymarket affair in Chicago.',
        1887: 'Construction of the Eiffel Tower begins.',
        1888: 'Jack the Ripper terrorizes London.',
        1889: 'Eiffel Tower is completed for the Exposition Universelle.',
        1890: 'Wounded Knee Massacre in the United States.',
        1891: 'The Great Blizzard of 1891 in the United States.',
        1892: 'Ellis Island opens as an immigration station.',
        1893: 'The Panic of 1893 leads to an economic depression.',
        1894: 'Pullman Strike in the United States.',
        1895: 'Wilhelm Roentgen discovers X-rays.',
        1896: 'Klondike Gold Rush begins.',
        1897: 'The Klondike Gold Rush peaks.',
        1898: 'Spanish-American War.',
        1899: 'Second Boer War begins.',
        1900: 'Boxer Rebellion in China.',
        1901: 'McKinley Assassination; Theodore Roosevelt becomes President.',
        1902: 'The world\'s first full-length feature film, "A Trip to the Moon," is released.',
        1903: 'Wright brothers make the first powered flight.',
        1904: 'Russo-Japanese War begins.',
        1905: 'Albert Einstein publishes the theory of relativity.',
        1906: 'San Francisco earthquake.',
        1907: 'Picasso paints "Les Demoiselles d\'Avignon."',
        1908: 'Ford Model T introduced.',
        1909: 'Robert Peary reaches the North Pole.',
        1910: 'Union of South Africa established.',
        1911: 'Chinese Revolution leads to the fall of the Qing Dynasty.',
        1912: 'The Titanic sinks.',
        1913: 'The Federal Reserve is established in the United States.',
        1914: 'World War I begins.',
        1915: 'The Armenian Genocide.',
        1916: 'Battle of the Somme.',
        1917: 'Russian Revolution.',
        1918: 'World War I ends.',
        1919: 'Treaty of Versailles signed.',
        1920: 'League of Nations established.',
        1921: 'The Irish Free State is founded.',
        1922: 'Howard Carter discovers Tutankhamun\'s tomb.',
        1923: 'The Great Kanto Earthquake in Japan.',
        1924: 'The first Winter Olympics are held.',
        1925: 'Scopes Monkey Trial in the United States.',
        1926: 'Route 66 is established.',
        1927: 'Charles Lindbergh makes the first solo nonstop transatlantic flight.',
        1928: 'Alexander Fleming discovers penicillin.',
        1929: 'Wall Street Crash; Great Depression begins.',
        1930: 'Mahatma Gandhi leads the Salt March.',
        1931: 'The Empire State Building is completed.',
        1932: 'The Great Depression intensifies.',
        1933: 'Adolf Hitler becomes Chancellor of Germany.',
        1934: 'Mao Zedong\'s Long March in China.',
        1935: 'Social Security Act signed in the United States.',
        1936: 'Berlin Olympics; Spanish Civil War begins.',
        1937: 'Marco Polo Bridge Incident; Second Sino-Japanese War begins.',
        1938: 'Kristallnacht in Nazi Germany.',
        1939: 'World War II begins.',
        1940: 'Battle of Britain.',
        1941: 'Pearl Harbor; United States enters World War II.',
        1942: 'Battle of Stalingrad.',
        1943: 'Warsaw Ghetto Uprising.',
        1944: 'D-Day; World War II intensifies.',
        1945: 'Atomic bombings of Hiroshima and Nagasaki; World War II ends.',
        1946: 'Nuremberg Trials.',
        1947: 'Partition of India; Cold War begins.',
        1948: 'Declaration of Human Rights adopted by the United Nations.',
        1949: 'NATO is established.',
        1950: 'Korean War begins.',
        1951: 'The Rosenbergs are executed for espionage in the United States.',
        1952: 'The first hydrogen bomb is detonated.',
        1953: 'Korean War ends; Stalin dies.',
        1954: 'Brown v. Board of Education; Algerian War begins.',
        1955: 'Montgomery Bus Boycott.',
        1956: 'Suez Crisis; Hungarian Uprising.',
        1957: 'Sputnik 1, the first artificial satellite, is launched.',
        1958: 'NASA is established.',
        1959: 'Cuban Revolution.',
        1960: 'The Greensboro Sit-ins begin.',
        1961: 'Bay of Pigs Invasion; Berlin Wall is constructed.',
        1962: 'Cuban Missile Crisis.',
        1963: 'March on Washington; JFK Assassination.',
        1964: 'Civil Rights Act passed in the United States.',
        1965: 'Voting Rights Act passed in the United States; Vietnam War escalates.',
        1966: 'Cultural Revolution begins in China.',
        1967: 'Six-Day War in the Middle East.',
        1968: 'Tet Offensive; Martin Luther King Jr. Assassination; Prague Spring.',
        1969: 'Woodstock Festival; Moon Landing.',
        1970: 'Kent State Shootings; Earth Day is established.',
        1971: 'Intel releases the first microprocessor.',
        1972: 'Watergate scandal begins; Munich Olympics massacre.',
        1973: 'Roe v. Wade; Vietnam War ends.',
        1974: 'Richard Nixon resigns.',
        1975: 'Fall of Saigon; Khmer Rouge takes over Cambodia.',
        1976: 'Apple is founded.',
        1977: 'Star Wars is released.',
        1978: 'Camp David Accords.',
        1979: 'Iranian Revolution; Soviet invasion of Afghanistan.',
        1980: 'Mount St. Helens eruption; Ronald Reagan elected President.',
        1981: 'AIDS is identified.',
        1982: 'Falklands War.',
        1983: 'Strategic Defense Initiative announced.',
        1984: 'Apple Macintosh is released.',
        1985: 'Mikhail Gorbachev becomes Soviet leader; Live Aid concerts.',
        1986: 'Chernobyl disaster.',
        1987: 'Intermediate-Range Nuclear Forces Treaty (INF) is signed.',
        1988: 'Pan Am Flight 103 bombing.',
        1989: 'Fall of the Berlin Wall; Tiananmen Square protests.',
        1990: 'German reunification; Nelson Mandela released from prison.',
        1991: 'Dissolution of the Soviet Union; Gulf War begins.',
        1992: 'Maastricht Treaty establishes the European Union.',
        1993: 'Oslo Accords; World Trade Center bombing.',
        1994: 'Nelson Mandela becomes President of South Africa.',
        1995: 'Dayton Agreement ends the Bosnian War; Oklahoma City bombing.',
        1996: 'Dolly the sheep, the first cloned mammal, is born.',
        1997: 'Hong Kong is handed back to China.',
        1998: 'Good Friday Agreement; Google is founded.',
        1999: 'Euro currency is introduced.',
        2000: 'Y2K fears; Sydney hosts the Summer Olympics.',
        2001: 'September 11 attacks on the World Trade Center and Pentagon.',
        2002: 'Euro currency becomes the official legal tender in twelve of the European Union\'s member states.',
        2003: 'Invasion of Iraq by the United States and its allies.',
        2004: 'Indian Ocean earthquake and tsunami.',
        2005: 'London bombings.',
        2006: 'Twitter is launched.',
        2007: 'Global financial crisis begins.',
        2008: 'Barack Obama is elected as the first African American President of the United States.',
        2009: 'Swine flu pandemic.',
        2010: 'Deepwater Horizon oil spill.',
        2011: 'Arab Spring uprisings.',
        2012: 'Curiosity rover lands on Mars.',
        2013: 'Edward Snowden leaks classified NSA documents.',
        2014: 'Ebola outbreak in West Africa.',
        2015: 'Paris terrorist attacks.',
        2016: 'United Kingdom votes to leave the European Union (Brexit).',
        2017: 'Solar eclipse visible across North America.',
        2018: 'North Korea and South Korea hold a historic summit.',
        2019: 'Notre-Dame Cathedral fire in Paris.',
        2020: 'COVID-19 pandemic begins.',
        2021: 'Joe Biden is inaugurated as the 46th President of the United States.', }
